### ISSUE TITLE
Mobile, can't vote or discuss

### ISSUE THREAD

**Issue by bjornlevi** [piratar/wasa2il#180] opened 2017-09-04 22:42 UTC
![screenshot_20170904-223931](https://user-images.githubusercontent.com/777264/30039553-2e014512-91c2-11e7-9e7b-7c2193118811.png)

Android, vote doesn't register and discussion form missing

**Comment by viktorsmari** [comment] 2017-09-05 07:38
We need more information, which browser?  It works on my Android, Chrome.

**Comment by bjornlevi** [comment] 2017-09-05 08:07
Android 7.1.1, chrome too.

The picture displays all I know. I can' see the discussions and vote doesn'
register. Verified by viewing the election on a PC.

Same when I request desktop site.

**Comment by bjornlevi** [comment] 2017-09-18 21:54
Actually I can't discuss on the web page either (although I can vote). No idea how to reproduce

![image](https://user-images.githubusercontent.com/777264/30566492-d254e1c4-9cbb-11e7-864f-7307518a663b.png)

**Comment by viktorsmari** [comment] 2017-09-19 07:26
I can't comment either in browser, but I can vote.. This is a critical bug.

**Comment by helgihg** [comment] 2017-09-27 15:25
I've tried the built-in browser and Chrome on one Android phone, and Chrome on a second device. I am unable to reproduce the bug. The symptoms are consistent with a networking error.

Seeing that there is not enough data to reproduce the problem, I'm concluding that this was some sort of temporary network problem and closing the issue.

**Closed by helgihg** 2017-09-27 15:25 UTC
