### ISSUE TITLE
initial_setup with python3 as default

### ISSUE THREAD

**Issue by bjornlevi** [piratar/wasa2il#49] opened 2016-02-03 13:00 UTC
Fails to install properly, setup needs to run pip2

**Comment by 7oi** [comment] 2017-06-05 17:11
Plenty more that requires adaptation to python3 standards. As python2's EOL is approaching in 2020, upgrading the whole project to python3 (and possibly upgrading to a more recent django version in the process) should be considered.

**Comment by helgihg** [comment] 2017-06-06 13:19
@7oi is right on both counts.

In fact, the Django version *needs* to be upgraded before the local elections, because 1.8's Long Term Support will probably be ended in April 2018.

The good news is that it's actually not nearly as difficult as it might seem.

**Comment by helgihg** [comment] 2017-10-17 15:58
I'm unable to reproduce this, and am not certain what's being asked, as a result. If it's about porting to Python 3, that's an effort that regards the project as a whole, and is not scheduled yet, at least not until Wasa2il's Django has been upgraded to 1.11 first (which needs to happen before April 2018, as previously mentioned).

Seeing that I'm unable to reproduce this, I'm closing this issue. Please re-open with more detail if needed.

**Closed by helgihg** 2017-10-17 15:58 UTC
