### ISSUE TITLE
Ability for candidate to drop bid from running election

### ISSUE THREAD

**Issue by helgihg** [piratar/wasa2il#178] opened 2017-08-29 19:05 UTC
A candidate in a running election should be able to drop their bid themselves, without the assistance of technicians.

**Comment by BjarniRunar** [comment] 2017-09-23 16:52
Maybe.

This means all the people who voted for them have had their ballots "edited" against their wishes. I didn't implement this because I was concerned that some of the counting algorithms might have problems with "ballots with holes in them".

When this happens, should something notify the people who voted for that candidate? That has anonymity consequences...

In many ways, it's cleanest to handle these users all at once at the end of the election with a recount.

**Comment by BjarniRunar** [comment] 2017-09-23 23:04
Another factor I forgot to mention: although of course it needs to be possible to withdraw, it shouldn't really be easy or encouraged. Running for office is a serious thing and jerking voters around is rude.

If the UI makes withdrawing a casual thing that involves no effort, that's sending The Wrong Message (tm).

**Comment by viktorsmari** [comment] 2017-09-24 14:42
I agree with @BjarniRunar, running for office is a serious thing and should not be 'super easy' to cancel with one click or something like that.
I liked in the last election, some candidates who were dropping out for whatever reason, simply renamed their profile username to something like 'NOT RUNNING' and removed their profile picture.
That gave the voters who checked their ballot before the deadline, the opportunity to catch it. We could encourage this approach until we find a viable solution.

**Comment by viktorsmari** [comment] 2017-09-24 14:43
But we might have a vote on something less serious in the future, where you should not need a technician to help you withdraw. Especially if the software scales, we should not need a technician removing people from elections full time.

**Comment by BjarniRunar** [comment] 2017-09-25 09:32
This is a duplicate of #120 - closing as such, will comment there that folks should also check this issue for discussion.

**Closed by BjarniRunar** 2017-09-25 09:32 UTC
