### ISSUE TITLE
UI desing

### ISSUE THREAD

**Issue by bjornlevi** [piratar/wasa2il#61] opened 2016-05-21 15:32 UTC
Currently the system has never had a complete useability and appearance design. The system needs a style guide and serious useability analysis.

**Comment by helgihg** [comment] 2017-10-07 19:02
While the issue is true, it's not an actionable item, so I'm closing it for now. We'll open up a bunch of these once we're in a position for UI overhaul. It won't be just one issue, so much is certain. ;)

**Closed by helgihg** 2017-10-07 19:02 UTC
Labels: enhancement
